services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: admin
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql
    ports:
      - 3330:3300

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8030:80
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin

  app:
    build: ./php
    ports:
      - 8031:80
    volumes:
      - ./src:/var/www/html
    environment:
      - APP_ENV=dev
